name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
  schedule:
    - cron: '00 1 1 * *'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      imageid: ${{ steps.bap.outputs.imageid }}
      digest: ${{ steps.bap.outputs.digest }}
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      -
        name: Build and push
        id: bap
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: |
            teejo75/steamcmd-base:latest
            ghcr.io/teejo75/steamcmd-base:latest
  
  internal-dispatch:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      -
        name: Notify Downstream Repository
        uses: peter-evans/repository-dispatch@v4.0.1
        with:
          token: ${{ secrets.PAT_STEAMCMD_WINE }}
          repository: teejo75/steamcmd-wine
          event-type: steamcmd-base-updated
          client-payload: |
            {
              "imageid": "${{ needs.build-and-push.outputs.imageid }}",
              "digest": "${{ needs.build-and-push.outputs.digest }}"
            }
